/**
 * Application runtime integration (KC-005).
 *
 * Digital Rafeeq Runtime lives beside the application — it does not replace it.
 */

export {
  RuntimeProvider,
  getRuntimeBootstrapResult,
  getRuntimeBootstrapStatus,
  initializeRuntime,
  useCommunication,
  useConversationEngine,
  useGuidance,
  useRuntime,
  type RuntimeBootstrapResult,
  type RuntimeBootstrapStatus,
  type RuntimeContextValue,
} from './bootstrap'

export {
  CampaignRepositoryAdapter,
  ComplianceRepositoryAdapter,
  KarkunRepositoryAdapter,
  MeetingRepositoryAdapter,
  ReportRepositoryAdapter,
  RepositoryAdapterFactory,
  createRepositoryAdapterFactory,
  createRepositoryAdapters,
  registerRepositoryAdapters,
  type RepositoryAdapterSet,
} from './adapters'

export {
  CampaignKnowledgeProvider,
  ComplianceKnowledgeProvider,
  KarkunKnowledgeProvider,
  KnowledgeProviderFactory,
  MeetingKnowledgeProvider,
  ReportKnowledgeProvider,
  createKnowledgeProviderFactory,
  createKnowledgeProviders,
  registerKnowledgeProviders,
  type LiveKnowledgeProviderSet,
} from './knowledge'

export {
  ConversationOrchestrator,
  ConversationSessionManager,
  createConversationOrchestrator,
  createConversationSessionManager,
  planForIntent,
  type CommunicationComposedOrchestrationEvent,
  type ContextResolvedOrchestrationEvent,
  type ConversationCompletedOrchestrationEvent,
  type ConversationFailedOrchestrationEvent,
  type ConversationIntent,
  type ConversationInterruptedOrchestrationEvent,
  type ConversationOrchestratorOptions,
  type ConversationRequest,
  type ConversationResponse,
  type ConversationResumedOrchestrationEvent,
  type ConversationStartedOrchestrationEvent,
  type GuidanceGeneratedOrchestrationEvent,
  type KnowledgeDomainPlan,
  type KnowledgeResolvedOrchestrationEvent,
  type KnowledgeSummary,
  type OrchestrationEvent,
  type OrchestrationEventListener,
  type OrchestrationEventType,
  type OrchestrationHealthStatus,
  type OrchestrationIdentity,
  type OrchestrationSessionRecord,
  type OrchestrationStageName,
  type OrchestrationTiming,
} from './orchestration'

export {
  DIGITAL_RAFEEQ_INTENTS,
  DIGITAL_RAFEEQ_ROLES,
  DigitalRafeeqService,
  createDigitalRafeeqService,
  getDigitalRafeeqService,
  resetDigitalRafeeqServiceForTests,
  type CommunicationReadyEvent,
  type ConversationCompletedEvent,
  type ConversationFailedEvent,
  type ConversationInterruptedEvent,
  type ConversationStartedEvent,
  type DigitalRafeeqError,
  type DigitalRafeeqEvent,
  type DigitalRafeeqEventListener,
  type DigitalRafeeqEventType,
  type DigitalRafeeqExecutionMetadata,
  type DigitalRafeeqHealth,
  type DigitalRafeeqHealthStatus,
  type DigitalRafeeqIdentity,
  type DigitalRafeeqIntent,
  type DigitalRafeeqRequest,
  type DigitalRafeeqResponse,
  type DigitalRafeeqServiceOptions,
  type DigitalRafeeqSession,
  type DigitalRafeeqStatus,
  type DigitalRafeeqTiming,
  type GuidanceGeneratedEvent,
  type RuntimeReadyEvent,
} from './service'
