/**
 * KC-029 / KC-034 — Urdu copy for the executive Campaign Report.
 * Natural Jamaat administrative tone; Connection ≠ Visit throughout.
 */

export const URDU_REPORT = {
  documentTitle: 'کارکن کنیکٹ جائزہ رپورٹ',
  subtitle: 'مہم کی پیش رفت کا انتظامی جائزہ',
  organizationDefault: 'جماعتِ اسلامی ہند · باساواکلیان',
  productName: 'Karkun Connect',

  cover: {
    section: 'سرورق',
    campaignName: 'مہم کا نام',
    campaignDuration: 'مہم کی مدت',
    reportPeriod: 'رپورٹ کی مدت',
    organization: 'ادارہ / تنظیم',
    reportDate: 'رپورٹ کی تاریخ',
    generatedDate: 'تاریخِ تیاری',
    generatedTime: 'وقتِ تیاری',
    generatedOn: 'تیار کرنے کا وقت',
    generatedBy: 'تیار کنندہ',
    campaignStatus: 'مہم کی حیثیت',
    campaignDay: 'مہم کا دن',
  },

  sections: {
    cover: 'سرورق',
    executive: 'انتظامی خلاصہ',
    executiveSummary: 'انتظامی خلاصہ',
    campaignStatus: 'مہم کی حیثیت',
    organization: 'تنظیم',
    campaignSummary: 'مہم کا خلاصہ',
    campaignProgress: 'مہم کی پیش رفت',
    keyStatistics: 'اہم اعداد و شمار',
    overallProgress: 'مجموعی مہم کی پیش رفت',
    achievement: 'مجموعی کارکردگی',
    campaignAchievements: 'مہم کی کامیابیاں',
    remainingObjectives: 'باقی مقاصد',
    priorityActions: 'ترجیحی اقدامات',
    closingSummary: 'اختتامی خلاصہ',
    appendix: 'ضمیمہ',
    malePerformance: 'ارکان کی کارکردگی (مرد)',
    femalePerformance: 'ارکان کی کارکردگی (خواتین)',
    individualPerformance: 'ارکان کی تفصیل',
    pending: 'امور زیر التواء',
    critical: 'فوری توجہ درکار',
    progressBands: 'ارکان کی پیش رفت — زمرے',
    followUp: 'فالو اپ فہرستیں',
    topPerformers: 'نمایاں کارکردگی',
    categoryLeaders: 'شعبہ جاتی نمایاں کارکردگی',
    statistics: 'مجموعی اعداد و شمار',
    recommendations: 'تجاویز',
  },

  v2: {
    campaign: 'مہم',
    overallProgress: 'مجموعی پیش رفت',
    daysCompleted: 'مکمل ایام',
    daysRemaining: 'باقی ایام',
    remainingConnections: 'باقی رابطے',
    emptyAchievements: 'ابھی کوئی قابلِ ذکر کامیابی ریکارڈ نہیں ہوئی۔',
    emptyRemaining: 'اس وقت کوئی باقی مقصد نہیں۔',
    emptyPriorities: 'فوری ترجیحی اقدام درکار نہیں۔',
    closingWithPriorities: 'ترجیحی اقدامات پر عمل درآمد جاری رکھیے۔',
    closingSteady: 'موجودہ رفتار برقرار رکھیے۔',
    achievements: {
      orgFoundation: 'تنظیمی بنیاد تیار',
      digitalRegistry: 'ڈیجیٹل رجسٹری مکمل',
      connectionSystem: 'رابطہ نظام قائم',
      firstPhase: 'پہلا مرحلہ مکمل',
      muttafiqeenRegistry: 'متفقین رجسٹری تیار',
      ruknComplete: 'ارکان کی مہم مکمل',
      visitsProgress: 'ملاقاتوں میں پیش رفت',
    },
    remaining: {
      connections: 'باقی رابطے',
      visits: 'ملاقاتیں',
      weeklyIjtema: 'ہفتہ وار اجتماع',
      baitulMaal: 'بیت المال',
      appRegistration: 'ایپ رجسٹریشن',
      muttafiqeen: 'متفقین رجسٹری کی تکمیل',
      followUp: 'فالو اپ',
    },
  },

  progressBands: {
    notStarted: 'شروع نہیں ہوا (۰٪)',
    initial: 'ابتدائی پیش رفت (۱–۴۰٪)',
    nearComplete: 'قریب تکمیل (۴۱–۹۹٪)',
    complete: 'مہم مکمل (۱۰۰٪)',
    count: 'تعداد',
    names: 'نام',
    empty: 'اس زمرے میں کوئی رکن نہیں۔',
  },

  followUp: {
    visitPending: 'ملاقات زیر التواء',
    appRegistrationPending: 'ایپ رجسٹریشن زیر التواء',
    weeklyIjtemaFollowUp: 'ہفتہ وار اجتماع — فالو اپ',
    baitulMaalFollowUp: 'بیت المال — فالو اپ',
    empty: 'اس فہرست میں کوئی رکن نہیں۔',
  },

  recommendationTiers: {
    urgent: 'فوری کارروائی',
    next: 'اگلا مرحلہ',
    positive: 'مثبت پیش رفت',
  },

  kpi: {
    totalRukns: 'کل ارکان',
    maleRukns: 'مرد',
    femaleRukns: 'خواتین',
    totalKarkuns: 'کل کارکن',
    maleKarkuns: 'مرد',
    femaleKarkuns: 'خواتین',
    totalMuttafiqeen: 'کل متفقین',
    maleMuttafiqeen: 'مرد متفقین',
    femaleMuttafiqeen: 'خواتین متفقین',
    connectedKarkuns: 'منسلک کارکنان',
    connectionPct: 'رابطوں کی شرح',
    visits: 'ملاقاتیں',
    appRegistration: 'ایپ رجسٹریشن',
    weeklyIjtema: 'ہفتہ وار اجتماع',
    baitulMaal: 'بیت المال',
    overallProgress: 'مجموعی پیش رفت',
    rukn: 'رکن',
    karkun: 'کارکن',
  },

  columns: {
    rukn: 'رکن',
    assigned: 'کل کارکن',
    maleKarkuns: 'مرد کارکن',
    femaleKarkuns: 'خواتین کارکن',
    totalKarkuns: 'کل کارکن',
    maleMuttafiqeen: 'مرد متفقین',
    femaleMuttafiqeen: 'خواتین متفقین',
    totalMuttafiqeen: 'کل متفقین',
    connected: 'رابطے',
    visits: 'ملاقات',
    appRegistration: 'ایپ رجسٹریشن',
    weeklyIjtema: 'ہفتہ وار اجتماع',
    baitulMaal: 'بیت المال',
    overall: 'مجموعی پیش رفت',
    pending: 'زیر التواء',
    pendingActivities: 'زیر التواء سرگرمیاں',
    value: 'قدر',
    area: 'شعبہ',
    completed: 'مکمل',
    total: 'کل',
    category: 'زمرہ',
    leader: 'نمایاں رکن',
    result: 'نتیجہ',
    reasons: 'توجہ کی وجوہات',
    rank: 'درجہ',
    score: 'کارکردگی اسکور',
    overallLabel: 'مجموعی',
    male: 'مرد',
    female: 'خواتین',
    muttafiqeen: 'متفقین',
    completion: 'تکمیل',
  },

  achievementAreas: {
    connections: 'رابطے',
    visits: 'ملاقاتیں',
    appRegistration: 'ایپ رجسٹریشن',
    weeklyIjtema: 'ہفتہ وار اجتماع',
    baitulMaal: 'بیت المال',
  },

  topCategories: {
    connections: 'رابطے',
    visits: 'ملاقاتیں',
    appRegistration: 'ایپ رجسٹریشن',
    weeklyIjtema: 'ہفتہ وار اجتماع',
    baitulMaal: 'بیت المال',
    overall: 'مجموعی پیش رفت',
    mostImproved: 'نمایاں بہتری',
  },

  empty: {
    noRukns: 'اس سیکشن میں کوئی رکن موجود نہیں۔',
    noPending: 'کسی رکن کے پاس امور زیر التواء نہیں۔',
    noCritical: 'فوری توجہ کے مستحق کوئی رکن نہیں۔',
    noRecommendations: 'اس زمرے میں کوئی تجویز نہیں۔',
    noCategoryLeader: 'فی الحال اس شعبہ میں کوئی نمایاں کارکردگی موجود نہیں۔',
    noTopPerformers: 'فی الحال کوئی نمایاں کارکردگی موجود نہیں۔',
  },

  status: {
    active: 'فعال',
    archived: 'محفوظ شدہ',
    none: 'کوئی فعال مہم نہیں',
    notSet: 'طے شدہ نہیں',
  },

  footer: {
    generatedBy: 'تیار کردہ: Karkun Connect',
    reportDate: 'تاریخِ تیاری',
    generatedAt: 'وقتِ تیاری',
    campaignDuration: 'مہم کی مدت',
    systemVersion: 'نظام کا ورژن',
    disclaimer: 'یہ رپورٹ خودکار طور پر تیار کی گئی ہے۔',
    page: 'صفحہ',
    of: 'از',
  },

  button: 'مہم کی رپورٹ (PDF)',
} as const

export const URDU_CRITICAL_REASONS = {
  noConnections: 'رابطے شروع نہیں ہوئے',
  lowVisits: 'ملاقاتیں کم ہیں',
  lowWeeklyIjtema: 'ہفتہ وار اجتماع کی حاضری کم ہے',
  lowAppRegistration: 'ایپ رجسٹریشن کم ہے',
  lowBaitulMaal: 'بیت المال کی پیش رفت کم ہے',
  lowOverall: 'مجموعی پیش رفت کم ہے',
} as const
