/**
 * KC-029 — Urdu copy for the executive Campaign Report.
 */

export const URDU_REPORT = {
  documentTitle: 'کارکن کنیکٹ جائزہ رپورٹ',
  subtitle: 'مہم کی پیش رفت کا انتظامی جائزہ',
  organizationDefault: 'جماعتِ اسلامی ہند · باساواکلیان',
  productName: 'Karkun Connect',

  cover: {
    section: 'سرورق',
    campaignName: 'مہم کا نام',
    campaignDuration: 'مہم کی مدت',
    reportPeriod: 'رپورٹ کی مدت',
    organization: 'ادارہ / تنظیم',
    reportDate: 'رپورٹ کی تاریخ',
    generatedDate: 'تاریخِ تیاری',
    generatedTime: 'وقتِ تیاری',
    generatedOn: 'تیار کرنے کا وقت',
    generatedBy: 'تیار کنندہ',
    campaignStatus: 'مہم کی حیثیت',
    campaignDay: 'مہم کا دن',
  },

  sections: {
    cover: 'سرورق',
    executive: 'کارکردگی کا خلاصہ',
    campaignProgress: 'مہم کی پیش رفت',
    overallProgress: 'مجموعی مہم کی پیش رفت',
    achievement: 'مجموعی کارکردگی',
    malePerformance: 'ارکان کی کارکردگی (مرد)',
    femalePerformance: 'ارکان کی کارکردگی (خواتین)',
    individualPerformance: 'انفرادی کارکردگی',
    pending: 'امور زیر التواء',
    critical: 'فوری توجہ درکار',
    topPerformers: 'نمایاں کارکردگی',
    categoryLeaders: 'شعبہ جاتی نمایاں کارکردگی',
    statistics: 'مجموعی اعداد و شمار',
    recommendations: 'اہم مشاہدات اور آئندہ اقدامات',
  },

  recommendationTiers: {
    urgent: 'فوری توجہ درکار',
    next: 'اگلا مرحلہ',
    positive: 'مثبت پیش رفت',
  },

  kpi: {
    totalRukns: 'کل ارکان',
    maleRukns: 'مرد ارکان',
    femaleRukns: 'خواتین ارکان',
    totalKarkuns: 'کل کارکن',
    maleKarkuns: 'مرد کارکن',
    femaleKarkuns: 'خواتین کارکن',
    totalMuttafiqeen: 'کل متفقین',
    maleMuttafiqeen: 'مرد متفقین',
    femaleMuttafiqeen: 'خواتین متفقین',
    peopleCovered: 'کل افرادِ زیرِ کوریج',
    connectedKarkuns: 'منسلک کارکنان',
    connectionPct: 'منسلک ہونے کی شرح',
    visits: 'ملاقاتیں',
    appRegistration: 'جے آئی ایچ رپورٹنگ ایپ',
    weeklyIjtema: 'ہفتہ وار اجتماع',
    baitulMaal: 'بیت المال',
    overallProgress: 'مجموعی پیش رفت',
  },

  columns: {
    rukn: 'رکن',
    assigned: 'کل کارکن',
    maleKarkuns: 'مرد کارکن',
    femaleKarkuns: 'خواتین کارکن',
    totalKarkuns: 'کل کارکن',
    maleMuttafiqeen: 'مرد متفقین',
    femaleMuttafiqeen: 'خواتین متفقین',
    totalMuttafiqeen: 'کل متفقین',
    connected: 'رابطے',
    visits: 'ملاقات',
    appRegistration: 'ایپ رجسٹریشن',
    weeklyIjtema: 'ہفتہ وار اجتماع',
    baitulMaal: 'بیت المال',
    overall: 'مجموعی پیش رفت',
    pending: 'زیر التواء',
    pendingActivities: 'زیر التواء سرگرمیاں',
    value: 'قدر',
    area: 'شعبہ',
    completed: 'مکمل',
    total: 'کل',
    category: 'زمرہ',
    leader: 'نمایاں رکن',
    result: 'نتیجہ',
    reasons: 'توجہ کی وجوہات',
    rank: 'درجہ',
    score: 'کارکردگی اسکور',
    overallLabel: 'مجموعی',
    male: 'مرد',
    female: 'خواتین',
    muttafiqeen: 'متفقین',
    completion: 'تکمیل',
  },

  achievementAreas: {
    connections: 'رابطے',
    visits: 'ملاقاتیں',
    appRegistration: 'ایپ رجسٹریشن',
    weeklyIjtema: 'ہفتہ وار اجتماع',
    baitulMaal: 'بیت المال عزم',
  },

  topCategories: {
    connections: 'منسلک کارکنان',
    visits: 'بہترین ملاقات کارکردگی',
    appRegistration: 'بہترین ایپ رجسٹریشن',
    weeklyIjtema: 'بہترین ہفتہ وار اجتماع',
    baitulMaal: 'بہترین بیت المال',
    overall: 'مجموعی پیش رفت',
    mostImproved: 'سب سے نمایاں بہتری',
  },

  empty: {
    noRukns: 'اس سیکشن میں کوئی رکن موجود نہیں۔',
    noPending: 'کسی رکن کے پاس امور زیر التواء نہیں۔',
    noCritical: 'فوری توجہ کے مستحق کوئی رکن نہیں ملا۔',
    noRecommendations: 'اس زمرے میں کوئی مشاہدہ نہیں۔',
  },

  status: {
    active: 'فعال',
    archived: 'محفوظ شدہ',
    none: 'کوئی فعال مہم نہیں',
    notSet: 'طے شدہ نہیں',
  },

  footer: {
    generatedBy: 'تیار کردہ: Karkun Connect',
    reportDate: 'تاریخِ تیاری',
    generatedAt: 'وقتِ تیاری',
    campaignDuration: 'مہم کی مدت',
    systemVersion: 'نظام کا ورژن',
    disclaimer: 'یہ رپورٹ خودکار طور پر تیار کی گئی ہے۔',
    page: 'صفحہ',
    of: 'از',
  },

  button: 'مہم کی رپورٹ (PDF)',
} as const

export const URDU_CRITICAL_REASONS = {
  noConnections: 'کوئی منسلک کارکن نہیں',
  lowVisits: 'ملاقاتوں کی تکمیل کم ہے',
  lowWeeklyIjtema: 'ہفتہ وار اجتماع کی حاضری کم ہے',
  lowAppRegistration: 'ایپ رجسٹریشن کم ہے',
  lowBaitulMaal: 'بیت المال کی پیش رفت کم ہے',
  lowOverall: 'مجموعی پیش رفت کم ہے',
} as const
