/**
 * KC-0114 — Campaign Report PDF generator (presentation only).
 * Browser PDF via jsPDF + autotable (reportlab-class professional tables).
 */

import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import {
  buildCampaignReportModel,
  type CampaignReportMetricPair,
  type CampaignReportModel,
  type CampaignReportRuknRow,
} from './campaignReportModel'

type JsPdfWithAutoTable = jsPDF & {
  lastAutoTable?: { finalY: number }
}

function metricCell(metric: CampaignReportMetricPair): string {
  return `${metric.completed}/${metric.total}`
}

function pendingCell(metric: CampaignReportMetricPair): string {
  return String(metric.pending)
}

function addFooter(doc: jsPDF, generatedOn: string) {
  const pageCount = doc.getNumberOfPages()
  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page)
    const width = doc.internal.pageSize.getWidth()
    const height = doc.internal.pageSize.getHeight()
    doc.setDrawColor(200)
    doc.line(14, height - 16, width - 14, height - 16)
    doc.setFontSize(8)
    doc.setTextColor(100)
    doc.text('Generated by Karkun Connect · Campaign Execution Platform', 14, height - 10)
    doc.text(generatedOn, width / 2, height - 10, { align: 'center' })
    doc.text(`Page ${page} of ${pageCount}`, width - 14, height - 10, { align: 'right' })
  }
}

function ensureSpace(doc: JsPdfWithAutoTable, y: number, needed = 40): number {
  const pageHeight = doc.internal.pageSize.getHeight()
  if (y + needed < pageHeight - 22) return y
  doc.addPage()
  return 20
}

function sectionTitle(doc: JsPdfWithAutoTable, title: string, y: number): number {
  const nextY = ensureSpace(doc, y, 16)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(13)
  doc.setTextColor(20)
  doc.text(title, 14, nextY)
  doc.setDrawColor(37, 99, 235)
  doc.setLineWidth(0.4)
  doc.line(14, nextY + 2, 80, nextY + 2)
  return nextY + 8
}

function kvBlock(
  doc: JsPdfWithAutoTable,
  rows: Array<[string, string]>,
  startY: number,
): number {
  let y = startY
  doc.setFontSize(10)
  for (const [label, value] of rows) {
    y = ensureSpace(doc, y, 8)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(60)
    doc.text(`${label}:`, 14, y)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(20)
    doc.text(value, 58, y)
    y += 6
  }
  return y + 4
}

function ruknPerformanceTable(
  doc: JsPdfWithAutoTable,
  title: string,
  rows: CampaignReportRuknRow[],
  startY: number,
): number {
  const y = sectionTitle(doc, title, startY)
  if (rows.length === 0) {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.text('No Rukns in this section.', 14, y)
    return y + 8
  }

  autoTable(doc, {
    startY: y,
    head: [
      [
        'Rukn',
        'Assigned',
        'Connected',
        'Visits',
        'App Reg.',
        'Weekly Ijtema',
        'Baitul Maal',
        'Overall %',
      ],
    ],
    body: rows.map((row) => [
      row.ruknName,
      String(row.assignedKarkuns),
      metricCell(row.connections),
      metricCell(row.visits),
      metricCell(row.appRegistration),
      metricCell(row.weeklyIjtema),
      metricCell(row.baitulMaal),
      `${row.overallPct}%`,
    ]),
    styles: { fontSize: 8, cellPadding: 2, overflow: 'linebreak', valign: 'middle' },
    headStyles: { fillColor: [30, 64, 175], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    margin: { left: 14, right: 14, bottom: 22 },
    rowPageBreak: 'avoid',
  })

  return (doc.lastAutoTable?.finalY ?? y) + 10
}

export function downloadCampaignReportPdf(options?: {
  generatedBy?: string
  organization?: string
  model?: CampaignReportModel
}): CampaignReportModel {
  const model = options?.model ?? buildCampaignReportModel({
    generatedBy: options?.generatedBy,
    organization: options?.organization,
  })
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' }) as JsPdfWithAutoTable
  const pageWidth = doc.internal.pageSize.getWidth()

  // Cover
  doc.setFillColor(30, 64, 175)
  doc.rect(0, 0, pageWidth, 42, 'F')
  doc.setTextColor(255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(18)
  doc.text('Campaign Report', 14, 18)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.text('Karkun Connect · Leadership Review Pack', 14, 26)
  doc.setFontSize(10)
  doc.text(model.cover.campaignName, 14, 34)

  let y = 52
  y = sectionTitle(doc, '1. Cover', y)
  y = kvBlock(doc, [
    ['Campaign Name', model.cover.campaignName],
    ['Campaign Duration', model.cover.campaignDuration],
    ['Organization', model.cover.organization],
    ['Report Date', model.cover.reportDate],
    ['Generated On', model.cover.generatedOn],
    ['Generated By', model.cover.generatedBy],
    ['Campaign Status', model.cover.campaignStatus],
  ], y)

  // Executive summary
  y = sectionTitle(doc, '2. Executive Summary', y)
  autoTable(doc, {
    startY: y,
    head: [['KPI', 'Value']],
    body: [
      ['Total Rukns', String(model.executive.totalRukns)],
      ['Male Rukns', String(model.executive.maleRukns)],
      ['Female Rukns', String(model.executive.femaleRukns)],
      ['Total Karkuns', String(model.executive.totalKarkuns)],
      [
        'Connected Karkuns',
        `${model.executive.connected.completed} / ${model.executive.connected.total}`,
      ],
      ['Connection %', `${model.executive.connectionPct}%`],
      ['Visits Conducted', metricCell(model.executive.visits)],
      ['JIH Reporting App Registered', metricCell(model.executive.appRegistration)],
      ['Weekly Ijtema Attendance', metricCell(model.executive.weeklyIjtema)],
      ['Baitul Maal Commitment', metricCell(model.executive.baitulMaal)],
      ['Overall Campaign Progress', `${model.executive.overallCampaignProgress}%`],
    ],
    styles: { fontSize: 9, cellPadding: 2.5 },
    headStyles: { fillColor: [30, 64, 175] },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 70 } },
    margin: { left: 14, right: 14, bottom: 22 },
    rowPageBreak: 'avoid',
  })
  y = (doc.lastAutoTable?.finalY ?? y) + 10

  // Achievement
  y = sectionTitle(doc, '3. Campaign Achievement', y)
  autoTable(doc, {
    startY: y,
    head: [['Area', 'Completed / Total', 'Pending', 'Progress %']],
    body: model.achievement.map((item) => [
      item.label,
      metricCell(item.metric),
      pendingCell(item.metric),
      `${item.metric.pct}%`,
    ]),
    styles: { fontSize: 9, cellPadding: 2.5 },
    headStyles: { fillColor: [30, 64, 175] },
    margin: { left: 14, right: 14, bottom: 22 },
    rowPageBreak: 'avoid',
  })
  y = (doc.lastAutoTable?.finalY ?? y) + 10

  y = ruknPerformanceTable(doc, '4. Male Rukn Performance', model.maleRukns, y)
  y = ruknPerformanceTable(doc, '5. Female Rukn Performance', model.femaleRukns, y)

  // Pending work
  y = sectionTitle(doc, '6. Pending Work', y)
  if (model.pendingByRukn.length === 0) {
    doc.setFontSize(10)
    doc.text('No pending work across Rukns.', 14, y)
    y += 8
  } else {
    autoTable(doc, {
      startY: y,
      head: [
        [
          'Rukn',
          'Connections Pending',
          'Visits Pending',
          'App Reg. Pending',
          'Weekly Ijtema Pending',
          'Baitul Maal Pending',
        ],
      ],
      body: model.pendingByRukn.map((row) => [
        row.ruknName,
        pendingCell(row.connections),
        pendingCell(row.visits),
        pendingCell(row.appRegistration),
        pendingCell(row.weeklyIjtema),
        pendingCell(row.baitulMaal),
      ]),
      styles: { fontSize: 8, cellPadding: 2 },
      headStyles: { fillColor: [30, 64, 175] },
      margin: { left: 14, right: 14, bottom: 22 },
      rowPageBreak: 'avoid',
    })
    y = (doc.lastAutoTable?.finalY ?? y) + 10
  }

  // Critical
  y = sectionTitle(doc, '7. Critical Rukns', y)
  if (model.criticalRukns.length === 0) {
    doc.setFontSize(10)
    doc.text('No critical Rukns identified.', 14, y)
    y += 8
  } else {
    autoTable(doc, {
      startY: y,
      head: [['Rukn', 'Overall %', 'Attention reasons']],
      body: model.criticalRukns.map((row) => [
        row.ruknName,
        `${row.overallPct}%`,
        row.criticalReasons.join('; '),
      ]),
      styles: { fontSize: 8, cellPadding: 2, overflow: 'linebreak' },
      headStyles: { fillColor: [185, 28, 28] },
      margin: { left: 14, right: 14, bottom: 22 },
      rowPageBreak: 'avoid',
    })
    y = (doc.lastAutoTable?.finalY ?? y) + 10
  }

  // Top performers
  y = sectionTitle(doc, '8. Top Performers', y)
  autoTable(doc, {
    startY: y,
    head: [['Category', 'Leader', 'Result']],
    body: model.topPerformers.map((row) => [row.category, row.ruknName, row.valueLabel]),
    styles: { fontSize: 9, cellPadding: 2.5 },
    headStyles: { fillColor: [21, 128, 61] },
    margin: { left: 14, right: 14, bottom: 22 },
    rowPageBreak: 'avoid',
  })
  y = (doc.lastAutoTable?.finalY ?? y) + 10

  // Statistics
  y = sectionTitle(doc, '9. Campaign Statistics', y)
  autoTable(doc, {
    startY: y,
    head: [['Area', 'Completed', 'Pending', 'Total']],
    body: model.statistics.map((item) => [
      item.label,
      String(item.metric.completed),
      String(item.metric.pending),
      String(item.metric.total),
    ]),
    styles: { fontSize: 9, cellPadding: 2.5 },
    headStyles: { fillColor: [30, 64, 175] },
    margin: { left: 14, right: 14, bottom: 22 },
    rowPageBreak: 'avoid',
  })
  y = (doc.lastAutoTable?.finalY ?? y) + 10

  // Recommendations
  y = sectionTitle(doc, '10. Operational Recommendations', y)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(20)
  for (const [index, line] of model.recommendations.entries()) {
    y = ensureSpace(doc, y, 14)
    const wrapped = doc.splitTextToSize(`${index + 1}. ${line}`, pageWidth - 28)
    doc.text(wrapped, 14, y)
    y += wrapped.length * 5 + 3
  }

  addFooter(doc, model.cover.generatedOn)

  const safeName = model.cover.campaignName.replace(/[^\w-]+/g, '_').slice(0, 48)
  doc.save(`Campaign_Report_${safeName || 'Active'}.pdf`)
  return model
}
