/**
 * KC-037C4 — Weekly Ijtema Attendance Report PDF (presentation only).
 * Reuses existing Urdu HTML → PDF pipeline (Executive Report V2 visual language).
 */

import type {
  WeeklyIjtemaAttendanceReportModel,
  WeeklyIjtemaRuknPerformanceRow,
} from './weeklyIjtemaAttendanceReportModel'
import { downloadUrduHtmlReportPdf, UrduHtml } from './urduHtmlToPdf'

function labels(lang: 'ur' | 'en') {
  if (lang === 'en') {
    return {
      executive: 'Executive Summary',
      overview: 'Attendance Overview',
      ruknPerformance: 'Rukn Performance',
      register: 'Attendance Register',
      absent: 'Absent Register',
      analytics: 'Attendance Analytics',
      insights: 'Operational Insights',
      recommendations: 'Operational Recommendations',
      appendix: 'Appendix',
      connected: 'Total Connected Karkuns',
      present: 'Present',
      absentCount: 'Absent',
      pending: 'Pending',
      attendancePct: 'Attendance %',
      malePct: 'Male Attendance %',
      femalePct: 'Female Attendance %',
      rank: 'Rank',
      rukn: 'Rukn',
      karkun: 'Karkun',
      attendance: 'Attendance',
      markedBy: 'Marked By',
      submissionTime: 'Submission Time',
      assignedRukn: 'Assigned Rukn',
      followUp: 'Follow-up Required',
      bestRukn: 'Best Performing Rukn',
      lowestRukn: 'Lowest Performing Rukn',
      highestPct: 'Highest Attendance %',
      lowestPct: 'Lowest Attendance %',
      overallPct: 'Overall Attendance %',
      genderCompare: 'Male / Female Comparison',
      byRukn: 'Attendance by Rukn',
      totals: 'Overall Totals',
      definitions: 'Attendance Definitions',
      generated: 'Generated Timestamp',
      reportVersion: 'Report Version',
      campaign: 'Campaign',
      reportingDate: 'Reporting Date',
      window: 'Attendance Window',
      generatedOn: 'Generated On',
      generatedBy: 'Generated By',
      emptyRegister: 'No attendance rows for this window.',
      emptyAbsent: 'No absent Karkuns — no follow-up list required.',
      emptyRukn: 'No Rukn attendance rows.',
    }
  }
  return {
    executive: 'انتظامی خلاصہ',
    overview: 'حاضری کا جائزہ',
    ruknPerformance: 'ارکان کی کارکردگی',
    register: 'حاضری رجسٹر',
    absent: 'غیر حاضر رجسٹر',
    analytics: 'حاضری تجزیہ',
    insights: 'آپریشنل مشاہدات',
    recommendations: 'آپریشنل تجاویز',
    appendix: 'ضمیمہ',
    connected: 'کل منسلک کارکنان',
    present: 'حاضر',
    absentCount: 'غیر حاضر',
    pending: 'زیر التواء',
    attendancePct: 'حاضری ٪',
    malePct: 'مرد حاضری ٪',
    femalePct: 'خواتین حاضری ٪',
    rank: 'رتبہ',
    rukn: 'رکن',
    karkun: 'کارکن',
    attendance: 'حاضری',
    markedBy: 'اندراج کنندہ',
    submissionTime: 'وقتِ اندراج',
    assignedRukn: 'مخصوص رکن',
    followUp: 'فالو اپ درکار',
    bestRukn: 'بہترین رکن',
    lowestRukn: 'کم ترین رکن',
    highestPct: 'سب سے زیادہ حاضری ٪',
    lowestPct: 'سب سے کم حاضری ٪',
    overallPct: 'مجموعی حاضری ٪',
    genderCompare: 'مرد / خواتین موازنہ',
    byRukn: 'رکن کے لحاظ سے حاضری',
    totals: 'مجموعی کل',
    definitions: 'حاضری کی تعریفات',
    generated: 'وقتِ تیاری',
    reportVersion: 'رپورٹ ورژن',
    campaign: 'مہم',
    reportingDate: 'تاریخِ رپورٹ',
    window: 'حاضری ونڈو',
    generatedOn: 'تیاری کی تاریخ',
    generatedBy: 'تیار کنندہ',
    emptyRegister: 'اس ونڈو کے لیے کوئی حاضری قطار نہیں۔',
    emptyAbsent: 'کوئی غیر حاضر کارکن نہیں — فالو اپ فہرست درکار نہیں۔',
    emptyRukn: 'کوئی رکن حاضری قطار نہیں۔',
  }
}

function kpi(label: string, value: string | number): string {
  return `
    <div class="kpi-card accent-navy">
      <p class="kpi-label">${UrduHtml.text(label)}</p>
      <p class="kpi-value">${UrduHtml.text(String(value))}</p>
    </div>
  `
}

function kvRow(label: string, value: string): string {
  return `
    <tr>
      <th>${UrduHtml.text(label)}</th>
      <td>${UrduHtml.text(value)}</td>
    </tr>
  `
}

function progressTone(pct: number): string {
  if (pct >= 90) return 'good'
  if (pct >= 70) return ''
  if (pct >= 40) return 'warn'
  return 'danger'
}

function progressBlock(label: string, pct: number): string {
  const tone = progressTone(pct)
  return `
    <div class="activity-card">
      <div class="act-head">
        <p class="act-title">${UrduHtml.text(label)}</p>
        <span class="act-pct">${UrduHtml.text(`${pct}٪`)}</span>
      </div>
      <div class="progress-track">
        <div class="progress-fill ${tone}" style="width:${Math.max(0, Math.min(100, pct))}%"></div>
      </div>
    </div>
  `
}

function rankBadgeClass(rank: number): string {
  if (rank <= 5) return `r${Math.min(rank, 5)}`
  return 'r5'
}

function highlightClass(row: WeeklyIjtemaRuknPerformanceRow): string {
  if (row.highlight === 'top5') return ' style="background:rgba(16,185,129,0.08)"'
  if (row.highlight === 'bottom5') return ' style="background:rgba(239,68,68,0.08)"'
  return ''
}

function buildWeeklyIjtemaAttendanceReportHtml(
  model: WeeklyIjtemaAttendanceReportModel,
): string {
  const L = labels(model.language)
  const parts: string[] = []
  const dirAttr = model.language === 'en' ? 'ltr' : 'rtl'
  const align = model.language === 'en' ? 'left' : 'right'
  const es = model.executiveSummary
  const ov = model.attendanceOverview

  // ── Cover + Executive Summary + Overview ──
  parts.push(`<section class="pdf-page" style="direction:${dirAttr};text-align:${align}">`)
  parts.push(`
    <header class="exec-header">
      <p class="v2-eyebrow">Karkun Connect · ${UrduHtml.text(model.appendix.reportVersion)}</p>
      <h1>${UrduHtml.text(model.cover.reportTitle)}</h1>
      <p class="campaign-name">${UrduHtml.text(model.cover.campaignUrdu)}</p>
      <div class="meta-row">
        <span class="meta-chip">${UrduHtml.text(L.campaign)}: ${UrduHtml.text(model.cover.campaignName)}</span>
        <span class="meta-chip">${UrduHtml.text(L.reportingDate)}: ${UrduHtml.text(model.cover.reportingDate)}</span>
        <span class="meta-chip">${UrduHtml.text(L.window)}: ${UrduHtml.text(model.cover.attendanceWindow)}</span>
        <span class="meta-chip">${UrduHtml.text(L.generatedOn)}: ${UrduHtml.text(model.cover.generatedOn)}</span>
        <span class="meta-chip">${UrduHtml.text(L.generatedBy)}: ${UrduHtml.text(model.cover.generatedBy)}</span>
      </div>
    </header>
  `)

  parts.push(UrduHtml.section(L.executive))
  parts.push(`<div class="v2-summary-card"><p>${UrduHtml.text(es.narrative)}</p></div>`)
  parts.push(`<div class="kpi-grid kpi-3">`)
  parts.push(kpi(L.connected, es.totalConnectedKarkuns))
  parts.push(kpi(L.present, es.present))
  parts.push(kpi(L.absentCount, es.absent))
  parts.push(kpi(L.pending, es.pending))
  parts.push(kpi(L.attendancePct, `${es.overallAttendancePct}٪`))
  parts.push(kpi(L.malePct, `${es.maleAttendancePct}٪`))
  parts.push(kpi(L.femalePct, `${es.femaleAttendancePct}٪`))
  parts.push(`</div>`)

  parts.push(UrduHtml.section(L.overview))
  parts.push(`<div class="kpi-grid kpi-3">`)
  parts.push(kpi(L.present, ov.present))
  parts.push(kpi(L.absentCount, ov.absent))
  parts.push(kpi(L.pending, ov.pending))
  parts.push(kpi(L.attendancePct, `${ov.attendancePct}٪`))
  parts.push(`</div>`)
  parts.push(progressBlock(L.attendancePct, ov.attendancePct))
  parts.push(`</section>`)

  // ── Rukn Performance ──
  const chunkSize = model.detailLevel === 'detailed' || model.detailLevel === 'audit' ? 14 : 16
  const ruknList = model.ruknPerformance
  for (let i = 0; i < ruknList.length || i === 0; i += chunkSize) {
    const chunk = ruknList.slice(i, i + chunkSize)
    parts.push(`<section class="pdf-page" style="direction:${dirAttr};text-align:${align}">`)
    parts.push(
      UrduHtml.section(
        i === 0 ? L.ruknPerformance : `${L.ruknPerformance} (${Math.floor(i / chunkSize) + 1})`,
      ),
    )
    if (chunk.length === 0) {
      parts.push(`<p class="v2-empty">${UrduHtml.text(L.emptyRukn)}</p>`)
    } else {
      const body = chunk
        .map(
          (row) => `
        <tr${highlightClass(row)}>
          <td><span class="rank-badge ${rankBadgeClass(row.rank)}">${UrduHtml.text(String(row.rank))}</span></td>
          <td class="name-cell">${UrduHtml.text(row.ruknName)}</td>
          <td>${UrduHtml.text(String(row.connected))}</td>
          <td>${UrduHtml.text(String(row.present))}</td>
          <td>${UrduHtml.text(String(row.absent))}</td>
          <td>${UrduHtml.text(`${row.attendancePct}٪`)}</td>
        </tr>`,
        )
        .join('')
      parts.push(`
        <div class="table-wrap">
          <table class="exec-table compact">
            <thead>
              <tr>
                <th>${UrduHtml.text(L.rank)}</th>
                <th>${UrduHtml.text(L.rukn)}</th>
                <th>${UrduHtml.text(L.connected)}</th>
                <th>${UrduHtml.text(L.present)}</th>
                <th>${UrduHtml.text(L.absentCount)}</th>
                <th>${UrduHtml.text(L.attendancePct)}</th>
              </tr>
            </thead>
            <tbody>${body}</tbody>
          </table>
        </div>
      `)
    }
    parts.push(`</section>`)
    if (ruknList.length === 0) break
  }

  // ── Attendance Register (grouped by Rukn) ──
  const register = model.attendanceRegister
  for (let i = 0; i < register.length || i === 0; i += chunkSize) {
    const chunk = register.slice(i, i + chunkSize)
    parts.push(`<section class="pdf-page" style="direction:${dirAttr};text-align:${align}">`)
    parts.push(
      UrduHtml.section(
        i === 0 ? L.register : `${L.register} (${Math.floor(i / chunkSize) + 1})`,
      ),
    )
    if (chunk.length === 0) {
      parts.push(`<p class="v2-empty">${UrduHtml.text(L.emptyRegister)}</p>`)
    } else {
      const body = chunk
        .map(
          (row) => `
        <tr>
          <td class="name-cell">${UrduHtml.text(row.karkunName)}</td>
          <td>${UrduHtml.text(row.ruknName)}</td>
          <td>${UrduHtml.text(row.attendance)}</td>
          <td>${UrduHtml.text(row.markedBy)}</td>
          <td>${UrduHtml.text(row.submissionTime)}</td>
        </tr>`,
        )
        .join('')
      parts.push(`
        <div class="table-wrap">
          <table class="exec-table compact">
            <thead>
              <tr>
                <th>${UrduHtml.text(L.karkun)}</th>
                <th>${UrduHtml.text(L.rukn)}</th>
                <th>${UrduHtml.text(L.attendance)}</th>
                <th>${UrduHtml.text(L.markedBy)}</th>
                <th>${UrduHtml.text(L.submissionTime)}</th>
              </tr>
            </thead>
            <tbody>${body}</tbody>
          </table>
        </div>
      `)
    }
    parts.push(`</section>`)
    if (register.length === 0) break
  }

  // ── Absent Register ──
  parts.push(`<section class="pdf-page" style="direction:${dirAttr};text-align:${align}">`)
  parts.push(UrduHtml.section(L.absent))
  if (model.absentRegister.length === 0) {
    parts.push(`<p class="v2-empty">${UrduHtml.text(L.emptyAbsent)}</p>`)
  } else {
    const body = model.absentRegister
      .map(
        (row) => `
      <tr>
        <td class="name-cell">${UrduHtml.text(row.karkunName)}</td>
        <td>${UrduHtml.text(row.ruknName)}</td>
        <td>${UrduHtml.text(row.assignedRuknName)}</td>
        <td>${UrduHtml.text(row.followUpRequired)}</td>
      </tr>`,
      )
      .join('')
    parts.push(`
      <div class="table-wrap">
        <table class="exec-table compact">
          <thead>
            <tr>
              <th>${UrduHtml.text(L.karkun)}</th>
              <th>${UrduHtml.text(L.rukn)}</th>
              <th>${UrduHtml.text(L.assignedRukn)}</th>
              <th>${UrduHtml.text(L.followUp)}</th>
            </tr>
          </thead>
          <tbody>${body}</tbody>
        </table>
      </div>
    `)
  }

  // ── Analytics + Insights + Recommendations ──
  const a = model.analytics
  parts.push(UrduHtml.section(L.analytics))
  parts.push(`<div class="table-wrap"><table class="exec-table compact"><tbody>`)
  parts.push(kvRow(L.bestRukn, a.bestPerformingRukn))
  parts.push(kvRow(L.lowestRukn, a.lowestPerformingRukn))
  parts.push(kvRow(L.highestPct, `${a.highestAttendancePct}٪`))
  parts.push(kvRow(L.lowestPct, `${a.lowestAttendancePct}٪`))
  parts.push(kvRow(L.overallPct, `${a.overallAttendancePct}٪`))
  parts.push(kvRow(L.genderCompare, a.maleFemaleComparison))
  parts.push(`</tbody></table></div>`)

  parts.push(UrduHtml.section(L.insights))
  parts.push(
    `<ul class="v2-list">${model.operationalInsights.map((x) => `<li>${UrduHtml.text(x)}</li>`).join('')}</ul>`,
  )

  parts.push(UrduHtml.section(L.recommendations))
  parts.push(
    `<ul class="v2-list">${model.operationalRecommendations.map((x) => `<li>${UrduHtml.text(x)}</li>`).join('')}</ul>`,
  )
  parts.push(`</section>`)

  // ── Appendix ──
  parts.push(`<section class="pdf-page" style="direction:${dirAttr};text-align:${align}">`)
  parts.push(UrduHtml.section(L.appendix))
  parts.push(`<p class="kpi-label">${UrduHtml.text(L.byRukn)}</p>`)
  {
    const body = model.appendix.attendanceByRukn
      .map(
        (row) => `
      <tr>
        <td class="name-cell">${UrduHtml.text(row.ruknName)}</td>
        <td>${UrduHtml.text(String(row.connected))}</td>
        <td>${UrduHtml.text(String(row.present))}</td>
        <td>${UrduHtml.text(String(row.absent))}</td>
        <td>${UrduHtml.text(String(row.pending))}</td>
        <td>${UrduHtml.text(`${row.attendancePct}٪`)}</td>
      </tr>`,
      )
      .join('')
    parts.push(`
      <div class="table-wrap">
        <table class="exec-table compact">
          <thead>
            <tr>
              <th>${UrduHtml.text(L.rukn)}</th>
              <th>${UrduHtml.text(L.connected)}</th>
              <th>${UrduHtml.text(L.present)}</th>
              <th>${UrduHtml.text(L.absentCount)}</th>
              <th>${UrduHtml.text(L.pending)}</th>
              <th>${UrduHtml.text(L.attendancePct)}</th>
            </tr>
          </thead>
          <tbody>${body}</tbody>
        </table>
      </div>
    `)
  }

  const t = model.appendix.overallTotals
  parts.push(`<p class="kpi-label">${UrduHtml.text(L.totals)}</p>`)
  parts.push(`<div class="kpi-grid kpi-3">`)
  parts.push(kpi(L.connected, t.connected))
  parts.push(kpi(L.present, t.present))
  parts.push(kpi(L.absentCount, t.absent))
  parts.push(kpi(L.pending, t.pending))
  parts.push(kpi(L.attendancePct, `${t.attendancePct}٪`))
  parts.push(`</div>`)

  parts.push(`<p class="kpi-label">${UrduHtml.text(L.definitions)}</p>`)
  parts.push(
    `<ul class="v2-list">${model.appendix.definitions.map((x) => `<li>${UrduHtml.text(x)}</li>`).join('')}</ul>`,
  )

  parts.push(`<div class="table-wrap"><table class="exec-table compact"><tbody>`)
  parts.push(kvRow(L.generated, model.appendix.generatedTimestamp))
  parts.push(kvRow(L.reportVersion, model.appendix.reportVersion))
  parts.push(kvRow(L.campaign, model.appendix.campaign))
  parts.push(kvRow('Provider', model.appendix.providerVersion))
  parts.push(kvRow('Composer', model.appendix.composerVersion))
  parts.push(kvRow('System', model.appendix.systemVersion))
  parts.push(`</tbody></table></div>`)
  parts.push(`</section>`)

  return parts.join('\n')
}

export async function downloadWeeklyIjtemaAttendanceReportPdf(
  model: WeeklyIjtemaAttendanceReportModel,
): Promise<void> {
  const stamp = model.cover.reportingDate.replace(/[^\w-]+/g, '_').slice(0, 20)
  await downloadUrduHtmlReportPdf({
    title: model.cover.reportTitle,
    bodyHtml: buildWeeklyIjtemaAttendanceReportHtml(model),
    fileName: `Weekly_Ijtema_Attendance_${stamp || 'report'}.pdf`,
  })
}

/** HTML builder exported for evidence / preview screenshots. */
export function buildWeeklyIjtemaAttendanceReportHtmlForPreview(
  model: WeeklyIjtemaAttendanceReportModel,
): string {
  return buildWeeklyIjtemaAttendanceReportHtml(model)
}
