/**
 * KC-038C — Urdu copy for Weekly Ijtema Executive PDF.
 * Natural Urdu aligned with in-app Weekly Ijtema terminology.
 */

export const WI_EXEC_UR = {
  reportTitle: 'ہفتہ وار اجتماع کی جائزہ رپورٹ',
  campaignTagline: 'فعال کارکن، فعال جماعت',
  executiveSummary: 'انتظامی خلاصہ',
  executiveObservation: 'انتظامی مشاہدہ',
  comparisonGraph: 'یاد دہانی بمقابلہ شرکت',
  reportSubmitted: 'رپورٹ جمع کرنے والے ارکان',
  reportPending: 'رپورٹ جمع نہ کرنے والے ارکان',
  ruknDetail: 'رکن کی تفصیل',
  connectedKarkuns: 'منسلک کارکنان',
  followUpSection: 'اگلے ہفتے کے لیے فالو اپ',
  futureAnalytics: 'مستقبل کے تجزیات (جلد)',
  appendix: 'ضمیمہ',
  definitionsHeading: 'اصطلاحات',
  kpi: {
    connected: 'کل مربوط کارکنان',
    reminded: 'یاد دہانی کی گئی',
    present: 'اجتماع میں شریک ہوئے',
    absent: 'اجتماع میں شریک نہ ہوسکے',
    reportsSubmitted: 'رپورٹ جمع کرنے والے ارکان',
    reportsPending: 'رپورٹ جمع نہ کرنے والے ارکان',
    attendancePct: 'شرکت کی شرح',
  },
  table: {
    rukn: 'رکن',
    connected: 'مربوط',
    reminded: 'یاد دہانی',
    present: 'شرکت',
    absent: 'غیر شرکت',
    karkun: 'کارکن',
    status: 'کیفیت',
  },
  status: {
    present: 'اجتماع میں شریک ہوئے',
    absent: 'اجتماع میں شریک نہ ہوسکے',
    reminded: 'یاد دہانی کی گئی',
    pending: 'ابھی رابطہ باقی',
  },
  followUpGroups: {
    remindedOnly: 'صرف یاد دہانی — شرکت درج نہیں',
    absent: 'اجتماع میں شریک نہ ہوسکے',
  },
  graph: {
    reminded: 'یاد دہانی',
    attendance: 'شرکت',
    attendancePct: 'شرکت کی شرح',
  },
  meta: {
    meetingDate: 'تاریخِ اجتماع',
    generatedOn: 'تیاری کی تاریخ',
    generatedBy: 'تیار کنندہ',
    campaign: 'مہم',
  },
  future: [
    'ہفتہ وار حاضری کا رجحان',
    'یاد دہانی کا رجحان',
    'یاد دہانی بمقابلہ شرکت',
    'ماہانہ موازنہ',
    'مہم کی پیش رفت',
  ],
  definitionItems: [
    'یاد دہانی — اس ہفتے کے اجتماع کے لیے رکن نے کارکن سے رابطہ کیا۔',
    'اجتماع میں شریک — حاضری درج ہے۔',
    'اجتماع میں شریک نہ ہوسکے — غیر حاضری درج ہے۔',
    'شرکت کی شرح — شرکت ÷ یاد دہانی (کل)۔',
    'رپورٹ جمع — رکن نے اس ہفتے کی رپورٹ جمع کر دی۔',
  ],
} as const

export const WI_EXEC_EN = {
  reportTitle: 'Weekly Ijtema Executive Review Report',
  campaignTagline: 'Active Karkuns, Active Jamaat',
  executiveSummary: 'Executive Summary',
  executiveObservation: 'Executive Observation',
  comparisonGraph: 'Reminders vs Attendance',
  reportSubmitted: 'Rukns Who Submitted Reports',
  reportPending: 'Rukns With Pending Reports',
  ruknDetail: 'Rukn Detail',
  connectedKarkuns: 'Connected Karkuns',
  followUpSection: 'Follow-up for Next Week',
  futureAnalytics: 'Future Analytics (Coming Soon)',
  appendix: 'Appendix',
  definitionsHeading: 'Definitions',
  kpi: {
    connected: 'Total Connected Karkuns',
    reminded: 'Reminded',
    present: 'Attended',
    absent: 'Could Not Attend',
    reportsSubmitted: 'Reports Submitted',
    reportsPending: 'Reports Pending',
    attendancePct: 'Attendance Rate',
  },
  table: {
    rukn: 'Rukn',
    connected: 'Connected',
    reminded: 'Reminded',
    present: 'Present',
    absent: 'Absent',
    karkun: 'Karkun',
    status: 'Status',
  },
  status: {
    present: 'Attended',
    absent: 'Could not attend',
    reminded: 'Reminded',
    pending: 'Not yet contacted',
  },
  followUpGroups: {
    remindedOnly: 'Reminded only — attendance not recorded',
    absent: 'Could not attend',
  },
  graph: {
    reminded: 'Reminded',
    attendance: 'Attendance',
    attendancePct: 'Attendance %',
  },
  meta: {
    meetingDate: 'Meeting Date',
    generatedOn: 'Generated On',
    generatedBy: 'Generated By',
    campaign: 'Campaign',
  },
  future: [
    'Weekly Attendance Trend',
    'Reminder Trend',
    'Reminder vs Attendance Trend',
    'Monthly Comparison',
    'Campaign Progress Trend',
  ],
  definitionItems: [
    'Reminded — Rukn contacted the Karkun for this week’s Ijtema.',
    'Attended — present mark recorded.',
    'Could not attend — absent mark recorded.',
    'Attendance rate — Present ÷ Reminded (total).',
    'Report submitted — Rukn submitted this week’s report.',
  ],
} as const

export type WeeklyIjtemaExecutiveLabels =
  | typeof WI_EXEC_UR
  | typeof WI_EXEC_EN

export function weeklyIjtemaExecutiveLabels(lang: 'ur' | 'en'): WeeklyIjtemaExecutiveLabels {
  return lang === 'en' ? WI_EXEC_EN : WI_EXEC_UR
}
