/**
 * Karkun Connect — canonical icon names (M6.5 frozen).
 * Use only these names with the <Icon /> component.
 */
export type IconName =
  | 'home'
  | 'search'
  | 'users'
  | 'user'
  | 'chart'
  | 'link'
  | 'check'
  | 'refresh'
  | 'clipboard'
  | 'location'
  | 'phone'
  | 'sparkles'
  | 'plus'
  | 'x'
  | 'export'
  | 'mail'
  | 'megaphone'
  | 'settings'
  | 'help'
  | 'file-text'
  | 'message'
  | 'calendar'
  | 'eye'
  | 'menu'
  | 'bell'
  | 'warning'
  | 'clock'
  | 'handshake'
  | 'heart'
  | 'sprout'
  | 'flag'
  | 'circle'
  | 'circle-filled'
  | 'smartphone'
  | 'pulse-healthy'
  | 'pulse-attention'
  | 'pulse-critical'
