import type { KarkunRegistryRecord } from '@/types/karkun-registry.types'

export const MOCK_KARKUN_REGISTRY: KarkunRegistryRecord[] = [
  {
    id: 'kr-001',
    name: 'Mohammad Kareem',
    mobile: '+92 300 1234567',
    address: 'House 12, Street 4, ABC Colony',
    area: 'ABC Area',
    assignedRukn: 'Abdul Rahman',
    assignedRuknId: 'rukn-1',
    campaignStatus: 'active',
    jihRegistration: 'pending',
    visitStatus: 'scheduled',
    lastVisit: '2026-03-10',
    commitment: 'Attend weekly study circle',
    notes: 'Priority contact for JIH registration follow-up.',
    isArchived: false,
  },
  {
    id: 'kr-002',
    name: 'Ali Raza',
    mobile: '+92 301 2345678',
    address: 'Flat 3B, DEF Apartments',
    area: 'DEF Area',
    assignedRukn: 'Muhammad Hassan',
    assignedRuknId: 'rukn-2',
    campaignStatus: 'active',
    jihRegistration: 'approved',
    visitStatus: 'completed',
    lastVisit: '2026-03-11',
    commitment: null,
    notes: 'Regular participant in community programs.',
    isArchived: false,
  },
  {
    id: 'kr-003',
    name: 'Hamza Siddiqui',
    mobile: '+92 302 3456789',
    address: 'Plot 45, GHI Block',
    area: 'GHI Area',
    assignedRukn: 'Abdul Rahman',
    assignedRuknId: 'rukn-1',
    campaignStatus: 'active',
    jihRegistration: 'not_started',
    visitStatus: 'pending',
    lastVisit: null,
    commitment: 'Complete reading assignment',
    notes: 'New contact — first visit pending.',
    isArchived: false,
  },
  {
    id: 'kr-004',
    name: 'Bilal Hussain',
    mobile: '+92 303 4567890',
    address: 'House 8, JKL Street',
    area: 'JKL Area',
    assignedRukn: 'Ibrahim Khan',
    assignedRuknId: 'rukn-3',
    campaignStatus: 'inactive',
    jihRegistration: 'rejected',
    visitStatus: 'overdue',
    lastVisit: '2026-02-28',
    commitment: null,
    notes: 'Follow-up required for overdue visit.',
    isArchived: false,
  },
  {
    id: 'kr-005',
    name: 'Usman Farooq',
    mobile: '+92 304 5678901',
    address: 'MNO Lane, Sector 2',
    area: 'MNO Area',
    assignedRukn: 'Yusuf Ahmed',
    assignedRuknId: 'rukn-4',
    campaignStatus: 'active',
    jihRegistration: 'pending',
    visitStatus: 'scheduled',
    lastVisit: '2026-03-09',
    commitment: 'Join upcoming campaign event',
    notes: '',
    isArchived: false,
  },
  {
    id: 'kr-006',
    name: 'Tariq Mahmood',
    mobile: '+92 305 6789012',
    address: 'PQR Housing Society, Block C',
    area: 'PQR Area',
    assignedRukn: 'Muhammad Hassan',
    assignedRuknId: 'rukn-2',
    campaignStatus: 'active',
    jihRegistration: 'approved',
    visitStatus: 'completed',
    lastVisit: '2026-03-12',
    commitment: 'Monthly contribution pledge',
    notes: 'Reliable and responsive.',
    isArchived: false,
  },
  {
    id: 'kr-007',
    name: 'Saeed Anwar',
    mobile: '+92 306 7890123',
    address: 'STU Road, House 22',
    area: 'STU Area',
    assignedRukn: 'Ibrahim Khan',
    assignedRuknId: 'rukn-3',
    campaignStatus: 'not_assigned',
    jihRegistration: 'not_started',
    visitStatus: 'none',
    lastVisit: null,
    commitment: null,
    notes: 'Awaiting Rukn assignment.',
    isArchived: false,
  },
  {
    id: 'kr-008',
    name: 'Nadeem Akhtar',
    mobile: '+92 307 8901234',
    address: 'VWX Colony, Street 9',
    area: 'VWX Area',
    assignedRukn: 'Abdul Rahman',
    assignedRuknId: 'rukn-1',
    campaignStatus: 'active',
    jihRegistration: 'pending',
    visitStatus: 'pending',
    lastVisit: '2026-03-05',
    commitment: 'Follow up on JIH form',
    notes: 'Documents incomplete.',
    isArchived: false,
  },
  {
    id: 'kr-009',
    name: 'Farhan Qureshi',
    mobile: '+92 308 9012345',
    address: 'YZ Block, House 17',
    area: 'YZ Area',
    assignedRukn: 'Yusuf Ahmed',
    assignedRuknId: 'rukn-4',
    campaignStatus: 'inactive',
    jihRegistration: 'not_started',
    visitStatus: 'none',
    lastVisit: null,
    commitment: null,
    notes: 'Temporarily inactive this campaign.',
    isArchived: false,
  },
  {
    id: 'kr-010',
    name: 'Imran Shah',
    mobile: '+92 309 0123456',
    address: 'Central Plaza, Unit 5',
    area: 'Central Area',
    assignedRukn: 'Muhammad Hassan',
    assignedRuknId: 'rukn-2',
    campaignStatus: 'active',
    jihRegistration: 'approved',
    visitStatus: 'completed',
    lastVisit: '2026-03-12',
    commitment: 'Volunteer for next outreach',
    notes: 'Strong engagement history.',
    isArchived: false,
  },
  {
    id: 'kr-011',
    name: 'Khalid Mehmood',
    mobile: '+92 310 1234560',
    address: 'North Zone, Street 11',
    area: 'North Zone',
    assignedRukn: 'Abdul Rahman',
    assignedRuknId: 'rukn-1',
    campaignStatus: 'active',
    jihRegistration: 'not_started',
    visitStatus: 'scheduled',
    lastVisit: '2026-03-08',
    commitment: null,
    notes: '',
    isArchived: false,
  },
  {
    id: 'kr-012',
    name: 'Rashid Ali',
    mobile: '+92 311 2345670',
    address: 'East Zone, Block 7',
    area: 'East Zone',
    assignedRukn: 'Unassigned',
    assignedRuknId: '',
    campaignStatus: 'not_assigned',
    jihRegistration: 'not_started',
    visitStatus: 'none',
    lastVisit: null,
    commitment: null,
    notes: 'Recently added to registry.',
    isArchived: false,
  },
]

export function getKarkunById(id: string): KarkunRegistryRecord | undefined {
  return MOCK_KARKUN_REGISTRY.find((karkun) => karkun.id === id)
}

export function getRegistryFilterOptions() {
  const areas = [...new Set(MOCK_KARKUN_REGISTRY.map((k) => k.area))].sort()
  const rukns = [
    ...new Set(
      MOCK_KARKUN_REGISTRY.filter((k) => k.assignedRuknId).map((k) => k.assignedRukn),
    ),
  ].sort()

  return { areas, rukns }
}

export function adminKarkunProfilePath(karkunId: string): string {
  return `/admin/karkunan/${karkunId}`
}
