/**
 * KC-035B — Canonical intent codes (internal English enums).
 * User-facing responses remain Urdu (secretary style) — never expose these.
 */

export const IntentCode = {
  // Information
  SHOW_PERSON_DETAILS: 'SHOW_PERSON_DETAILS',
  SHOW_DASHBOARD: 'SHOW_DASHBOARD',
  SHOW_CAMPAIGN_STATUS: 'SHOW_CAMPAIGN_STATUS',
  SHOW_REPORT: 'SHOW_REPORT',
  SHOW_WEEKLY_IJTEMA: 'SHOW_WEEKLY_IJTEMA',
  SHOW_PENDING_TASKS: 'SHOW_PENDING_TASKS',

  // Updates
  RECORD_CONNECTION: 'RECORD_CONNECTION',
  RECORD_VISIT: 'RECORD_VISIT',
  RECORD_ATTENDANCE: 'RECORD_ATTENDANCE',
  RECORD_APP_REGISTRATION: 'RECORD_APP_REGISTRATION',
  RECORD_BAITUL_MAAL: 'RECORD_BAITUL_MAAL',

  // Navigation
  NAVIGATE_DASHBOARD: 'NAVIGATE_DASHBOARD',
  NAVIGATE_CAMPAIGN: 'NAVIGATE_CAMPAIGN',
  NAVIGATE_WORKERS: 'NAVIGATE_WORKERS',
  NAVIGATE_REPORTS: 'NAVIGATE_REPORTS',
  NAVIGATE_SETTINGS: 'NAVIGATE_SETTINGS',
  NAVIGATE_ACTIVITIES: 'NAVIGATE_ACTIVITIES',
  NAVIGATE_ATTENDANCE: 'NAVIGATE_ATTENDANCE',
  NAVIGATE_PAYMENT: 'NAVIGATE_PAYMENT',
  NAVIGATE_HOME: 'NAVIGATE_HOME',
  NAVIGATE_BACK: 'NAVIGATE_BACK',

  // Search
  FIND_PERSON: 'FIND_PERSON',
  FIND_RUKN: 'FIND_RUKN',
  FIND_CAMPAIGN: 'FIND_CAMPAIGN',

  // Administration
  GENERATE_REPORT: 'GENERATE_REPORT',
  ASSIGN_WORKER: 'ASSIGN_WORKER',
  ADD_WORKER: 'ADD_WORKER',
  EDIT_WORKER: 'EDIT_WORKER',

  // Conversation
  HELP: 'HELP',
  REPEAT: 'REPEAT',
  CANCEL: 'CANCEL',
  CONTINUE: 'CONTINUE',
  NEXT: 'NEXT',
  PREVIOUS: 'PREVIOUS',
  START_OVER: 'START_OVER',

  UNKNOWN: 'UNKNOWN',
} as const

export type IntentCode = (typeof IntentCode)[keyof typeof IntentCode]
