/**
 * KC-037B — Report type catalog (UI + Composer validation).
 * Only executive_campaign is fully available for PDF generation.
 */

import { KC034_EXECUTIVE_SECTION_ID } from './reportConfig'
import type { ReportTypeDefinition, ReportTypeId } from './types'

const EXECUTIVE_SECTIONS = [
  KC034_EXECUTIVE_SECTION_ID,
  'executive_summary',
  'kpi_dashboard',
  'mens_performance',
  'womens_performance',
  'weekly_ijtema',
  'visits',
  'baitul_maal',
  'app_registration',
  'connections',
  'top_performers',
  'recommendations',
  'rafeeq_insights',
  'muttafiqeen_summary',
]

export const REPORT_TYPE_CATALOG: ReportTypeDefinition[] = [
  {
    id: 'executive_campaign',
    title: 'Executive Campaign Report',
    description: 'Full management briefing (KC-034 Urdu PDF via Report Composer).',
    available: true,
    defaultScope: 'overall_campaign',
    defaultDetailLevel: 'standard',
    defaultOutput: 'pdf',
    sectionIds: EXECUTIVE_SECTIONS,
    featureFlag: true,
  },
  {
    id: 'campaign_progress',
    title: 'Campaign Progress Report',
    description: 'Progress-focused campaign view.',
    available: false,
    defaultScope: 'overall_campaign',
    defaultDetailLevel: 'standard',
    defaultOutput: 'pdf',
    sectionIds: ['kpi_dashboard', 'visits', 'connections'],
    featureFlag: false,
  },
  {
    id: 'men_performance',
    title: 'Men Performance Report',
    description: "Men's wing performance.",
    available: false,
    defaultScope: 'mens_wing',
    defaultDetailLevel: 'standard',
    defaultOutput: 'pdf',
    sectionIds: ['mens_performance'],
    featureFlag: false,
  },
  {
    id: 'women_performance',
    title: 'Women Performance Report',
    description: "Women's wing performance.",
    available: false,
    defaultScope: 'womens_wing',
    defaultDetailLevel: 'standard',
    defaultOutput: 'pdf',
    sectionIds: ['womens_performance'],
    featureFlag: false,
  },
  {
    id: 'rukn_performance',
    title: 'Rukn Performance Report',
    description: 'All Rukns scorecard.',
    available: false,
    defaultScope: 'overall_campaign',
    defaultDetailLevel: 'detailed',
    defaultOutput: 'pdf',
    sectionIds: ['individual_rukn_performance'],
    featureFlag: false,
  },
  {
    id: 'individual_rukn',
    title: 'Individual Rukn Report',
    description: 'Single Rukn dossier.',
    available: false,
    defaultScope: 'individual_rukn',
    defaultDetailLevel: 'detailed',
    defaultOutput: 'pdf',
    sectionIds: ['individual_rukn_performance'],
    featureFlag: false,
  },
  {
    id: 'individual_karkun',
    title: 'Individual Karkun Report',
    description: 'Single Karkun dossier.',
    available: false,
    defaultScope: 'individual_karkun',
    defaultDetailLevel: 'detailed',
    defaultOutput: 'pdf',
    sectionIds: ['individual_karkun_performance'],
    featureFlag: false,
  },
  {
    id: 'weekly_ijtema',
    title: 'Weekly Ijtema Report',
    description: 'Ijtema attendance analytics.',
    available: false,
    defaultScope: 'overall_campaign',
    defaultDetailLevel: 'standard',
    defaultOutput: 'pdf',
    sectionIds: ['weekly_ijtema'],
    featureFlag: false,
  },
  {
    id: 'visit_progress',
    title: 'Visit Progress Report',
    description: 'Personal visit progress (not Connection).',
    available: false,
    defaultScope: 'overall_campaign',
    defaultDetailLevel: 'standard',
    defaultOutput: 'pdf',
    sectionIds: ['visits'],
    featureFlag: false,
  },
  {
    id: 'baitul_maal',
    title: 'Baitul Maal Report',
    description: 'Monthly Baitul Maal compliance.',
    available: false,
    defaultScope: 'overall_campaign',
    defaultDetailLevel: 'standard',
    defaultOutput: 'pdf',
    sectionIds: ['baitul_maal'],
    featureFlag: false,
  },
  {
    id: 'app_registration',
    title: 'JIH App Registration Report',
    description: 'App registration progress.',
    available: false,
    defaultScope: 'overall_campaign',
    defaultDetailLevel: 'standard',
    defaultOutput: 'pdf',
    sectionIds: ['app_registration'],
    featureFlag: false,
  },
  {
    id: 'pending_activities',
    title: 'Pending Activities Report',
    description: 'Open operational work.',
    available: false,
    defaultScope: 'overall_campaign',
    defaultDetailLevel: 'standard',
    defaultOutput: 'pdf',
    sectionIds: ['pending_tasks'],
    featureFlag: false,
  },
  {
    id: 'communication',
    title: 'Communication Report',
    description: 'Communication status overview.',
    available: false,
    defaultScope: 'overall_campaign',
    defaultDetailLevel: 'standard',
    defaultOutput: 'pdf',
    sectionIds: ['communication_status'],
    featureFlag: false,
  },
  {
    id: 'follow_up',
    title: 'Follow-up Report',
    description: 'Follow-up and exceptions.',
    available: false,
    defaultScope: 'overall_campaign',
    defaultDetailLevel: 'standard',
    defaultOutput: 'pdf',
    sectionIds: ['recommendations'],
    featureFlag: false,
  },
  {
    id: 'muttafiqeen',
    title: 'Muttafiqeen Report',
    description: 'Muttafiqeen summary (outside campaign execution).',
    available: false,
    defaultScope: 'muttafiqeen_only',
    defaultDetailLevel: 'standard',
    defaultOutput: 'pdf',
    sectionIds: ['muttafiqeen_summary'],
    featureFlag: false,
  },
  {
    id: 'connections',
    title: 'Connection Report',
    description: 'Administrative Connection assignment progress (not Visits).',
    available: false,
    defaultScope: 'connected_only',
    defaultDetailLevel: 'standard',
    defaultOutput: 'pdf',
    sectionIds: ['connections'],
    featureFlag: false,
  },
  {
    id: 'snapshot_summary',
    title: 'Snapshot Summary Report',
    description: 'One-page snapshot.',
    available: false,
    defaultScope: 'overall_campaign',
    defaultDetailLevel: 'executive',
    defaultOutput: 'pdf',
    sectionIds: ['executive_summary', 'kpi_dashboard'],
    featureFlag: false,
  },
  {
    id: 'mathematical_audit',
    title: 'Mathematical Audit Report',
    description: 'Registry / connection reconciliation (ops).',
    available: false,
    defaultScope: 'entire_registry',
    defaultDetailLevel: 'audit',
    defaultOutput: 'pdf',
    sectionIds: ['data_quality'],
    featureFlag: false,
  },
  {
    id: 'integrity',
    title: 'Integrity Report',
    description: 'Integrity and exception audit.',
    available: false,
    defaultScope: 'entire_registry',
    defaultDetailLevel: 'audit',
    defaultOutput: 'pdf',
    sectionIds: ['data_quality'],
    featureFlag: false,
  },
  {
    id: 'historical_comparison',
    title: 'Historical Comparison Report',
    description: 'Period comparison — placeholder until history store exists.',
    available: false,
    defaultScope: 'campaign_comparison',
    defaultDetailLevel: 'detailed',
    defaultOutput: 'pdf',
    sectionIds: ['trend_analysis'],
    featureFlag: false,
  },
]

const byId = new Map(REPORT_TYPE_CATALOG.map((t) => [t.id, t]))

export function getReportType(id: ReportTypeId): ReportTypeDefinition | undefined {
  return byId.get(id)
}

export function listReportTypes(): ReportTypeDefinition[] {
  return [...REPORT_TYPE_CATALOG]
}

export function listAvailableReportTypes(): ReportTypeDefinition[] {
  return REPORT_TYPE_CATALOG.filter((t) => t.available && t.featureFlag)
}
