/** Central registry of persistence keys — stores must not reference these directly. */

export const STORAGE_KEYS = {
  ruknMaster: 'karkun-connect.rukn-master',
  karkunRegistry: 'karkun-connect.karkun-registry',
  karkunNextId: 'karkun-connect.karkun.next-id',
  aRuknCounter: 'karkun-connect.a-rukn-counter',
  migrationVersion: 'karkun-connect.migration.version',
  assignments: 'karkun-connect.assignments',
  assignmentSequence: 'karkun-connect.assignments.sequence',
  assignmentAsnRepairVersion: 'karkun-connect.assignments.asnRepairVersion',
  activityLog: 'karkun-connect.activity-log',
  annexure1: 'karkun-connect.annexure1',
  followUps: 'karkun-connect.followups',
  guidance: 'karkun-connect.guidance',
  communication: 'karkun-connect.communication',
  baitulMaal: 'karkun-connect.baitul-maal',
  ijtema: 'karkun-connect.ijtema',
  weeklyIjtemaEvents: 'karkun-connect.weekly-ijtema-events',
  weeklyIjtemaSubmissions: 'karkun-connect.weekly-ijtema-submissions',
  monthlyBaitulMaalCycles: 'karkun-connect.monthly-baitul-maal-cycles',
  monthlyBaitulMaalSubmissions: 'karkun-connect.monthly-baitul-maal-submissions',
  jihPortal: 'karkun-connect.jih-portal',
  broadcastLists: 'karkun-connect.broadcast-lists',
  migrationBackups: 'karkun-connect.migration.backups',
  karkunRequests: 'karkun-connect.karkun-requests',
  ruknAdminMessages: 'karkun-connect.rukn-admin-messages',
  connectionLedger: 'karkun-connect.connection-ledger',
  assignmentReviews: 'karkun-connect.assignment-reviews',
  muttafiqRelationships: 'karkun-connect.muttafiq-relationships',
  meqatiMansoobas: 'karkun-connect.meqati-mansoobas',
  planningObjectives: 'karkun-connect.planning-objectives',
  shobahs: 'karkun-connect.shobahs',
  units: 'karkun-connect.units',
  localProgrammes: 'karkun-connect.local-programmes',
  occurrences: 'karkun-connect.occurrences',
  responsibilities: 'karkun-connect.responsibilities',
  work: 'karkun-connect.work',
  userPreferences: 'karkun-connect.user-preferences',
  /** Phase 6 — per-user notification preference slice (SettingsRepository). */
  notificationPreferences: 'karkun-connect.notification-preferences',
  migrationBackup: (id: string) => `karkun-connect.migration.backup.${id}`,
} as const
