import { Link } from 'react-router-dom'
import { EnterpriseBadge, EnterpriseSectionHeader } from '@/components/enterprise'
import type { ReminderItem } from '@/types/campaignAutomation.types'

type CommandCenterRemindersProps = {
  reminders: ReminderItem[]
}

function urgencyVariant(priority: ReminderItem['priority']): 'danger' | 'warning' | 'info' | 'neutral' {
  if (priority <= 2) return 'danger'
  if (priority === 3) return 'warning'
  return 'info'
}

export function CommandCenterReminders({ reminders }: CommandCenterRemindersProps) {
  if (reminders.length === 0) {
    return (
      <section className="enterprise-card p-6">
        <EnterpriseSectionHeader
          title="Reminder Center"
          subtitle="Reminder Engine — no active reminders"
        />
        <p className="mt-4 text-sm text-secondary">Compliance and execution reminders are up to date.</p>
      </section>
    )
  }

  const grouped = {
    urgent: reminders.filter((item) => item.priority <= 2),
    soon: reminders.filter((item) => item.priority === 3),
    later: reminders.filter((item) => item.priority > 3),
  }

  const sections = [
    { key: 'urgent', label: 'Urgent', items: grouped.urgent },
    { key: 'soon', label: 'Due Soon', items: grouped.soon },
    { key: 'later', label: 'Upcoming', items: grouped.later },
  ].filter((section) => section.items.length > 0)

  return (
    <section className="enterprise-card p-6">
      <EnterpriseSectionHeader
        title="Reminder Center"
        subtitle="Generated by the Reminder Engine — grouped by urgency"
      />
      <div className="mt-4 space-y-5">
        {sections.map((section) => (
          <div key={section.key}>
            <h3 className="text-sm font-semibold text-text-heading">{section.label}</h3>
            <ul className="mt-2 space-y-2">
              {section.items.map((reminder) => (
                <li key={reminder.id}>
                  <Link
                    to={reminder.route}
                    className="enterprise-card-interactive flex items-start justify-between gap-3 p-4"
                  >
                    <span>
                      <span className="block text-sm font-semibold text-text-heading">
                        {reminder.label}
                      </span>
                      <span className="mt-0.5 block text-xs text-secondary">{reminder.reason}</span>
                    </span>
                    <EnterpriseBadge variant={urgencyVariant(reminder.priority)}>Act</EnterpriseBadge>
                  </Link>
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
    </section>
  )
}
