import { Link } from 'react-router-dom'
import { EnterpriseBadge, EnterpriseSectionHeader } from '@/components/enterprise'
import type { ScheduleItem } from '@/types/campaignAutomation.types'

type CommandCenterScheduleProps = {
  schedule: ScheduleItem[]
}

function priorityVariant(priority: ScheduleItem['priority']): 'danger' | 'warning' | 'info' | 'neutral' {
  if (priority === 1) return 'danger'
  if (priority === 2) return 'warning'
  if (priority === 3) return 'info'
  return 'neutral'
}

export function CommandCenterSchedule({ schedule }: CommandCenterScheduleProps) {
  return (
    <section id="todays-schedule" className="enterprise-card p-6">
      <EnterpriseSectionHeader
        title="Today's Schedule"
        subtitle="Generated by the Scheduling Engine — prioritized timeline"
      />

      {schedule.length === 0 ? (
        <p className="mt-4 text-sm text-secondary">No scheduled work for today.</p>
      ) : (
        <ol className="relative mt-6 space-y-0 border-l-2 border-primary-muted pl-6">
          {schedule.map((item) => (
            <li key={item.id} className="relative pb-6 last:pb-0">
              <span className="absolute -left-[calc(0.75rem+1px)] top-1 h-3 w-3 rounded-full border-2 border-primary bg-surface" />
              <Link
                to={item.route}
                className="enterprise-card-interactive block p-4"
              >
                <div className="flex flex-wrap items-start justify-between gap-2">
                  <span className="text-sm font-bold text-primary">{item.time}</span>
                  <EnterpriseBadge variant={priorityVariant(item.priority)}>
                    P{item.priority}
                  </EnterpriseBadge>
                </div>
                <p className="mt-2 text-sm font-semibold text-text-heading">{item.title}</p>
                {item.subtitle && (
                  <p className="mt-1 text-xs text-secondary">{item.subtitle}</p>
                )}
                <span className="mt-3 inline-block text-xs font-medium text-primary">Open →</span>
              </Link>
            </li>
          ))}
        </ol>
      )}
    </section>
  )
}
