export const PEOPLE_TABLE_WRAPPER_CLASS = 'ds-table-wrap hidden md:block'
export const PEOPLE_TABLE_CLASS = 'ds-table'
export const PEOPLE_TABLE_ROW_CLASS = 'ds-table-row'
export const PEOPLE_TABLE_CELL_CLASS = 'ds-table-cell'
export const PEOPLE_TABLE_NAME_CLASS = 'text-base font-semibold text-text-heading'
export const PEOPLE_TABLE_MOBILE_CLASS = 'text-[15px] text-secondary'
